version: '3.9'
services:
  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: JPQ3GZmKbXD*8*orcNFeXK
      MYSQL_DATABASE: woocommerce_sync
      MYSQL_USER: 3dprinter
      MYSQL_PASSWORD: De3DPrints!@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf

volumes:
  mysql_data:

